version: 2.1
orbs:
  nx: nrwl/nx@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
jobs:
  set-shas-integration-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - nx/set-shas
      - run:
          name: Check values
          shell: "/bin/bash"
          command: |
            HEAD_SHA=$(git rev-parse HEAD)
            if [[ $CIRCLE_BRANCH == "main" ]]; then
              BASE_SHA=$(git rev-parse origin/main~1)
            else
              BASE_SHA=$(git merge-base origin/main HEAD)
            fi
            echo "Comparing head: $NX_HEAD to $HEAD_SHA"
            echo "Comparing base: $NX_BASE to $BASE_SHA"
            if [[ $NX_HEAD == $HEAD_SHA && $NX_BASE == $BASE_SHA ]]; then
              echo "Test conditions met"
            else
              echo "Test conditions NOT met"
              exit 5
            fi

workflows:
  test-deploy:
    jobs:
      - set-shas-integration-test:
          filters: &filters
            tags:
              ignore: /.*/
      - orb-tools/pack:
          filters: &filters
            tags:
              only: /.*/
      - orb-tools/publish:
          orb-name: nrwl/nx
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - set-shas-integration-test
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
