description: >
  You can use `set-shas` without parameters using the default values provided. Check API for more information.
usage:
  version: 2.1
  orbs:
    nx: nrwl/nx@1.6.2
  jobs:
    build:
      docker:
        - image: cimg/node:14.17-browsers
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: yarn install --frozen-lockfile
        - nx/set-shas
        - run:
            name: Run Builds
            command: yarn nx affected --target=build --base=$NX_BASE --parallel --max-parallel=3
        - run:
            name: Run Unit Tests
            command: yarn nx affected --target=test --base=$NX_BASE --parallel --max-parallel=2
